#!/bin/sh
# Start/stop the bayeos-socket readout daemon.
#
### BEGIN INIT INFO
# Provides:          bayeos-socket
# Required-Start:    $local_fs $remote_fs $network $syslog $named 
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start bayeos-socket readout script
# Description:       bayeos-socket takes a socket to read data
### END INIT INFO



PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="bayeos-socket daemon"
NAME=bayeos-socket
DAEMON=/usr/sbin/bayeos-socket_start.sh
PIDFILE=/var/run/bayeos-socket.pid
SCRIPTNAME=/etc/init.d/"$NAME"

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

parse_environment () 
{
    for ENV_FILE in /etc/environment /etc/default/locale; do
        [ -r "$ENV_FILE" ] || continue
        [ -s "$ENV_FILE" ] || continue

         for var in LANG LANGUAGE LC_ALL LC_CTYPE; do
             value=`egrep "^${var}=" "$ENV_FILE" | tail -n1 | cut -d= -f2`
             [ -n "$value" ] && eval export $var=$value

             if [ -n "$value" ] && [ "$ENV_FILE" = /etc/environment ]; then
                 log_warning_msg "/etc/environment has been deprecated for locale information; use /etc/default/locale for $var=$value instead"
             fi
         done
     done

# Get the timezone set.
    if [ -z "$TZ" -a -e /etc/timezone ]; then
        TZ=`cat /etc/timezone` 
    fi
}

# Parse the system's environment
if [ "$READ_ENV" = "yes" ] ; then
    parse_environment
fi


case "$1" in
start)	log_daemon_msg "Starting $NAME" 
		[ -e "$PIDFILE" ] && status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || rm -f $PIDFILE
        start-stop-daemon --start --quiet --oknodo --make-pidfile --pidfile $PIDFILE  --name $NAME --background\
        --exec $DAEMON 
        log_end_msg $?
	;;
stop)	log_daemon_msg "Stopping $NAME"
		start-stop-daemon --stop --quiet --retry 60 --pidfile $PIDFILE
   		 RETVAL=$?
    	while ps -p `cat $PIDFILE` > /dev/null; do sleep 1; done
    	[ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
    	log_end_msg $RETVAL 
        ;;
restart) log_daemon_msg "Restarting $NAME" 
        $0 stop
        $0 start
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)	log_action_msg "Usage: /etc/init.d/bayeos-fifo {start|stop|status|restart}"
        exit 2
        ;;
esac
exit 0
